"""empty message

Revision ID: cc0345b01dde
Revises: a5cffa318ac2
Create Date: 2025-08-11 20:44:00.947934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0345b01dde'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('color_ojos', sa.String(length=50), nullable=False),
    sa.Column('color_cabello', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('fecha_subscripcion', sa.DateTime(), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('fecha_subscripcion')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('personaje')
    # ### end Alembic commands ###
