"""empty message

Revision ID: d4f937e12099
Revises: cc0345b01dde
Create Date: 2025-08-11 20:55:57.381230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f937e12099'
down_revision = 'cc0345b01dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.Column('clima', sa.String(length=50), nullable=False),
    sa.Column('terreno', sa.String(length=50), nullable=False),
    sa.Column('poblacion', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planeta')
    # ### end Alembic commands ###
